# Source Prezto.
if [[ -f "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source ~/.myenv

# Source gruvbox 256 color palette.
if [[ -d ~/.vim/plugged/gruvbox ]]; then
  source ~/.vim/plugged/gruvbox/gruvbox_256palette.sh
fi
